cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
]

finalproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls', namespace='catalogue')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

catalogue/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=126)
    slug = models.SlugField(max_length=126, unique=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('catalogue:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Producer(models.Model):
    name = models.CharField(max_length=126)
    slug = models.SlugField(max_length=126, unique=True)

    # TODO logo = models.ImageField(upload_to='uploads/')

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.PROTECT)
    producer = models.ForeignKey(Producer, related_name='producers', on_delete=models.PROTECT)
    slug = models.SlugField(max_length=128, unique=True)
    name = models.CharField(max_length=126)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')

    # TODO: thumbnail = models.ImageField(upload_to='uploads/', blank=True, null=True)

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('catalogue:product_detail', args=[self.slug])

    def __str__(self):
        return self.name

cart/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from catalogue.models import Product


def cart_summary(request):
    cart = Cart(request)
    return render(request, 'catalogue/cart/summary.html', {'cart': cart})


def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)

        cart_total_qty = cart.__len__()
        response = JsonResponse({'qty': cart_total_qty})

        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)

        cart_total_qty = cart.__len__()
        cart_total_price = cart.get_total_price()
        response = JsonResponse({'qty': cart_total_qty, 'subtotal': cart_total_price})
        return response


def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        cart.update(product=product_id, qty=product_qty)

        cart_total_qty = cart.__len__()
        cart_total_price = cart.get_total_price()
        response = JsonResponse({'qty': cart_total_qty, 'subtotal': cart_total_price})
        return response

catalogue/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Producer, Product


def categories(request):
    return {
        'categories': Category.objects.all()
    }


def products_all(request):
    products = Product.objects.filter(is_active=True)
    return render(request, 'catalogue/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'catalogue/products/detail.html', {'product': product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category, is_active=True)
    return render(request, 'catalogue/products/category.html',
                  {'category': category,
                   'products': products
                   }
                  )

templates/catalogue/cart/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
    Cart Summary
{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2">Your Basket</h1>
    </div>
    <div class="col-12">
      <p>Manage your <b>items</b> in your basket</p>
    </div>
    <hr />
  </div>
  <div class="container" style="max-width: 1000px">

    <div class="row g-3">
      <div class="col-12 bg-light p-3 d-flex justify-content-between">
        <div class="d-flex d-flex-inline">
          <div class="pe-3">Order</div>
          <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
          Shipping options
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
          </svg>
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">Next day delivery</li>
            <li class="item small">Premimum delivery</li>
          </ul>
          </div>
        </div>
        <div class="text-end">

          <div class="">Sub Total: <span class="fw-bold">$</span><div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div></div>
          <div id="">Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold">$11.50</span></div>
          <div class="pt-2">Total to pay: <span class="fw-bold h5">$</span><span id="total" class="fw-bold h5">{{cart.get_total_price}}</span></div>

        </div>
      </div>
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
        <div class="d-grid gap-2 ">
          <a role="button" href="{% url "payment:cart" %}" class="btn btn-success fw-bold" type="button">Checkout</a>
          <button class="btn btn-light" type="button">Save for later</button>
        </div>
      </div>
      <div class="col-md-7 col-lg-8 p-0">

        {% for item in cart %}
        {% with product=item.product %}

        <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <img class="img-fluid mx-auto d-block" alt="Responsive image"
                  src="{{ product.image.url }}" />
            </div>
            <div class="col-md-10 ps-md-3">
              <div class="card-body p-1">
                <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                  <p class="card-text pb-3">{{product.name}}</p>
                </a>
                    <label for="select">Qty</label>
                    <select id="select{{product.id}}" style="width:50px;height:31px;">
                      <option value="" selected disabled hidden>{{item.qty}}</option>
                      <option value="">1</option>
                      <option value="">2</option>
                      <option value="">3</option>
                      <option value="">4</option>
                    </select>
                <a type="button" id="update-button" data-index="{{product.id}}" class="update-button text-decoration-none small ps-3">Update</a>
                <a type="button" id="delete-button" data-index="{{product.id}}" class="delete-button text-decoration-none small">Delete</a>
              </div>
            </div>
          </div>
        </div>
        {% endwith %}
        {% endfor %}
      </div>
    </div>

  </div>
</main>

<script>
    // Delete item from shopping cart
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var prod_id = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                $('.product-item[data-index="'+ prod_id +'"]').remove();

                if (json.qty === 0) {
                  total = 0
                  subtotal = 0
                } else {
                  total = (parseFloat(json.subtotal)).toFixed(2);
                  subtotal = json.subtotal
        }
                document.getElementById("subtotal").innerHTML = subtotal;
                document.getElementById("cart-qty").innerHTML = json.qty;
                document.getElementById("total").innerHTML = total;
            },
            error: function (xhr, errmsg, err) {}
        });
    })

    // Update quantity of items in shopping cart
    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var prod_id = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select'+ prod_id +' option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {

                if (json.qty === 0) {
                  total = 0
                  subtotal = 0
                } else {
                  total = (parseFloat(json.subtotal) + 11.50).toFixed(2);

            }
                document.getElementById("subtotal").innerHTML = json.subtotal;
                document.getElementById("cart-qty").innerHTML = json.qty;
                document.getElementById("total").innerHTML = total;
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}