account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from . forms import UserLoginForm


app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),

    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/delete_confirm.html"), name='delete_confirmation'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.products_all, name='products_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
]

finalproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls', namespace='catalogue')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogue/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=126)
    slug = models.SlugField(max_length=126, unique=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('catalogue:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Producer(models.Model):
    name = models.CharField(max_length=126)
    slug = models.SlugField(max_length=126, unique=True)

    # TODO logo = models.ImageField(upload_to='uploads/')

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.PROTECT)
    producer = models.ForeignKey(Producer, related_name='producers', on_delete=models.PROTECT)
    slug = models.SlugField(max_length=128, unique=True)
    name = models.CharField(max_length=126)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')

    # TODO: thumbnail = models.ImageField(upload_to='uploads/', blank=True, null=True)

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('catalogue:product_detail', args=[self.slug])

    def __str__(self):
        return self.name

catalogue/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Producer, Product


def categories(request):
    return {
        'categories': Category.objects.all()
    }


def products_all(request):
    products = Product.objects.filter(is_active=True)
    return render(request, 'catalogue/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'catalogue/products/detail.html', {'product': product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category, is_active=True)
    return render(request, 'catalogue/products/category.html',
                  {'category': category,
                   'products': products
                   }
                  )

templates/catalogue/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Final shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
          integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
          crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
          integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
          crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
          integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "base/css/base.css" %}">
    <link rel="stylesheet" href="{% static "cart/css/cart.css" %}">
</head>
<body>
        <header class="pb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid px-md-4">
                <div class="d-flex w-100 navbar-collapse">
                    <a class="navbar-brand d-flex-inline" href="/">
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                             class="bi bi-house" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5
                            1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0
                            1 .5.5z"/>
                            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0
                            1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                        </svg>
                    </a>
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Products
                                <i class="ps-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                            d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0
                                            1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                                    </svg></i>
                            </a>
                            <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "catalogue:products_all" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-list" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3
                                     7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0
                                     1H3a.5.5 0 0 1-.5-.5z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Shop</span>
                    </button>

                    {% if user.is_authenticated %}
                    <a type="button" role="button" href="{% url "account:logout" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1
                                    0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Logout</span>
                    </a>
                    {% else %}
                    <a type="button" role="button" href="{% url "account:login" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1
                                    0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Login</span>
                    </a>
                    {% endif %}


                    <a type="button" role="button" href=""
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0
                                    1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.
                                    516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832
                                    1.664h10z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Account</span>
                    </a>

                    <a type="button" role="button" href="{% url "cart:cart_summary" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">

                        {% with total_qty=cart|length %}
                        <div id="cart-qty" class="cart-qty">
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                 class="bi bi-bag" viewBox="0 0 16 16">
                                <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0
                                1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0
                                0 1-1-1V5z"/>
                            </svg>
                        </div>
                        <span class="fs15 fw500">Cart</span>
                    </a>
                </div>
                <div class="d-md-none d-lg-none d-xl-none">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li><a class="dropdown-item" href="{% url "catalogue:products_all" %}">All</a></li>
                            {% for c in categories %}
                            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <form class="d-flex w-100 d-md-none">
                    <input class="form-control me-2" type="search" placeholder="Search products or FAQ"
                        aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>

<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2021 Company, Inc</p>
  </footer>

</body>

</html>

templates/catalogue/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

<main>
  <div class="container">
    <div class="alert alert-primary fw600 rounded-0 border-0 py-3" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-info-circle me-2"
        viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
      </svg>
      COVID-19 - <u>Click here for our latest updates</u> on our stores, website and contact centre. Thank you for
      your patience and support.
    </div>
    <div class="container">
      <div class="row">
        <div class="album py-5">
          <div class="pb-3">
            <h1 class="h3">Popular</h1>
          </div>
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            {% for product in products %}
            <div class="col">
              <div class="card border-0">
                <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                <div class="card-body px-0">
                  <p class="card-text">
                    <a class="text-dark text-decoration-none"
                      href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                  </p>
                  <div class="fw-bold">${{product.price}}</div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}